/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-20 at 16:01:42 UTC 
 * Modify at your own risk.
 */

package com.appspot.myanhub_collabra.collabra;

/**
 * Service definition for Collabra (v1).
 *
 * <p>
 * API access for Collabra!
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CollabraRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Collabra extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.17.0-rc of the collabra library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myanhub-collabra.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "collabra/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Collabra(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Collabra(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Conversation collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Collabra collabra = new Collabra(...);}
   *   {@code Collabra.Conversation.List request = collabra.conversation().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Conversation conversation() {
    return new Conversation();
  }

  /**
   * The "conversation" collection of methods.
   */
  public class Conversation {

    /**
     * Create a request for the method "conversation.getById".
     *
     * This request holds the parameters needed by the collabra server.  After setting any optional
     * parameters, call the {@link GetById#execute()} method to invoke the remote operation.
     *
     * @param conversationId
     * @return the request
     */
    public GetById getById(java.lang.Long conversationId) throws java.io.IOException {
      GetById result = new GetById(conversationId);
      initialize(result);
      return result;
    }

    public class GetById extends CollabraRequest<com.appspot.myanhub_collabra.collabra.model.Conversation> {

      private static final String REST_PATH = "conversation/{conversationId}";

      /**
       * Create a request for the method "conversation.getById".
       *
       * This request holds the parameters needed by the the collabra server.  After setting any
       * optional parameters, call the {@link GetById#execute()} method to invoke the remote operation.
       * <p> {@link
       * GetById#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param conversationId
       * @since 1.13
       */
      protected GetById(java.lang.Long conversationId) {
        super(Collabra.this, "GET", REST_PATH, null, com.appspot.myanhub_collabra.collabra.model.Conversation.class);
        this.conversationId = com.google.api.client.util.Preconditions.checkNotNull(conversationId, "Required parameter conversationId must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetById setAlt(java.lang.String alt) {
        return (GetById) super.setAlt(alt);
      }

      @Override
      public GetById setFields(java.lang.String fields) {
        return (GetById) super.setFields(fields);
      }

      @Override
      public GetById setKey(java.lang.String key) {
        return (GetById) super.setKey(key);
      }

      @Override
      public GetById setOauthToken(java.lang.String oauthToken) {
        return (GetById) super.setOauthToken(oauthToken);
      }

      @Override
      public GetById setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetById) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetById setQuotaUser(java.lang.String quotaUser) {
        return (GetById) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetById setUserIp(java.lang.String userIp) {
        return (GetById) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long conversationId;

      /**

       */
      public java.lang.Long getConversationId() {
        return conversationId;
      }

      public GetById setConversationId(java.lang.Long conversationId) {
        this.conversationId = conversationId;
        return this;
      }

      @Override
      public GetById set(String parameterName, Object value) {
        return (GetById) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "conversation.insert".
     *
     * This request holds the parameters needed by the collabra server.  After setting any optional
     * parameters, call the {@link Insert#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.myanhub_collabra.collabra.model.Conversation}
     * @return the request
     */
    public Insert insert(com.appspot.myanhub_collabra.collabra.model.Conversation content) throws java.io.IOException {
      Insert result = new Insert(content);
      initialize(result);
      return result;
    }

    public class Insert extends CollabraRequest<com.appspot.myanhub_collabra.collabra.model.JsonMap> {

      private static final String REST_PATH = "conversation";

      /**
       * Create a request for the method "conversation.insert".
       *
       * This request holds the parameters needed by the the collabra server.  After setting any
       * optional parameters, call the {@link Insert#execute()} method to invoke the remote operation.
       * <p> {@link
       * Insert#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.myanhub_collabra.collabra.model.Conversation}
       * @since 1.13
       */
      protected Insert(com.appspot.myanhub_collabra.collabra.model.Conversation content) {
        super(Collabra.this, "POST", REST_PATH, content, com.appspot.myanhub_collabra.collabra.model.JsonMap.class);
      }

      @Override
      public Insert setAlt(java.lang.String alt) {
        return (Insert) super.setAlt(alt);
      }

      @Override
      public Insert setFields(java.lang.String fields) {
        return (Insert) super.setFields(fields);
      }

      @Override
      public Insert setKey(java.lang.String key) {
        return (Insert) super.setKey(key);
      }

      @Override
      public Insert setOauthToken(java.lang.String oauthToken) {
        return (Insert) super.setOauthToken(oauthToken);
      }

      @Override
      public Insert setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Insert) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Insert setQuotaUser(java.lang.String quotaUser) {
        return (Insert) super.setQuotaUser(quotaUser);
      }

      @Override
      public Insert setUserIp(java.lang.String userIp) {
        return (Insert) super.setUserIp(userIp);
      }

      @Override
      public Insert set(String parameterName, Object value) {
        return (Insert) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the User collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Collabra collabra = new Collabra(...);}
   *   {@code Collabra.User.List request = collabra.user().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public User user() {
    return new User();
  }

  /**
   * The "user" collection of methods.
   */
  public class User {

    /**
     * Create a request for the method "user.delete".
     *
     * This request holds the parameters needed by the collabra server.  After setting any optional
     * parameters, call the {@link Delete#execute()} method to invoke the remote operation.
     *
     * @param userId
     * @return the request
     */
    public Delete delete(java.lang.Long userId) throws java.io.IOException {
      Delete result = new Delete(userId);
      initialize(result);
      return result;
    }

    public class Delete extends CollabraRequest<Void> {

      private static final String REST_PATH = "user/{userId}";

      /**
       * Create a request for the method "user.delete".
       *
       * This request holds the parameters needed by the the collabra server.  After setting any
       * optional parameters, call the {@link Delete#execute()} method to invoke the remote operation.
       * <p> {@link
       * Delete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param userId
       * @since 1.13
       */
      protected Delete(java.lang.Long userId) {
        super(Collabra.this, "DELETE", REST_PATH, null, Void.class);
        this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      }

      @Override
      public Delete setAlt(java.lang.String alt) {
        return (Delete) super.setAlt(alt);
      }

      @Override
      public Delete setFields(java.lang.String fields) {
        return (Delete) super.setFields(fields);
      }

      @Override
      public Delete setKey(java.lang.String key) {
        return (Delete) super.setKey(key);
      }

      @Override
      public Delete setOauthToken(java.lang.String oauthToken) {
        return (Delete) super.setOauthToken(oauthToken);
      }

      @Override
      public Delete setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Delete) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Delete setQuotaUser(java.lang.String quotaUser) {
        return (Delete) super.setQuotaUser(quotaUser);
      }

      @Override
      public Delete setUserIp(java.lang.String userIp) {
        return (Delete) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long userId;

      /**

       */
      public java.lang.Long getUserId() {
        return userId;
      }

      public Delete setUserId(java.lang.Long userId) {
        this.userId = userId;
        return this;
      }

      @Override
      public Delete set(String parameterName, Object value) {
        return (Delete) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "user.getById".
     *
     * This request holds the parameters needed by the collabra server.  After setting any optional
     * parameters, call the {@link GetById#execute()} method to invoke the remote operation.
     *
     * @param userId
     * @return the request
     */
    public GetById getById(java.lang.Long userId) throws java.io.IOException {
      GetById result = new GetById(userId);
      initialize(result);
      return result;
    }

    public class GetById extends CollabraRequest<com.appspot.myanhub_collabra.collabra.model.User> {

      private static final String REST_PATH = "user/{userId}";

      /**
       * Create a request for the method "user.getById".
       *
       * This request holds the parameters needed by the the collabra server.  After setting any
       * optional parameters, call the {@link GetById#execute()} method to invoke the remote operation.
       * <p> {@link
       * GetById#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param userId
       * @since 1.13
       */
      protected GetById(java.lang.Long userId) {
        super(Collabra.this, "GET", REST_PATH, null, com.appspot.myanhub_collabra.collabra.model.User.class);
        this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetById setAlt(java.lang.String alt) {
        return (GetById) super.setAlt(alt);
      }

      @Override
      public GetById setFields(java.lang.String fields) {
        return (GetById) super.setFields(fields);
      }

      @Override
      public GetById setKey(java.lang.String key) {
        return (GetById) super.setKey(key);
      }

      @Override
      public GetById setOauthToken(java.lang.String oauthToken) {
        return (GetById) super.setOauthToken(oauthToken);
      }

      @Override
      public GetById setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetById) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetById setQuotaUser(java.lang.String quotaUser) {
        return (GetById) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetById setUserIp(java.lang.String userIp) {
        return (GetById) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long userId;

      /**

       */
      public java.lang.Long getUserId() {
        return userId;
      }

      public GetById setUserId(java.lang.Long userId) {
        this.userId = userId;
        return this;
      }

      @Override
      public GetById set(String parameterName, Object value) {
        return (GetById) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "user.getByUsername".
     *
     * This request holds the parameters needed by the collabra server.  After setting any optional
     * parameters, call the {@link GetByUsername#execute()} method to invoke the remote operation.
     *
     * @param username
     * @return the request
     */
    public GetByUsername getByUsername(java.lang.String username) throws java.io.IOException {
      GetByUsername result = new GetByUsername(username);
      initialize(result);
      return result;
    }

    public class GetByUsername extends CollabraRequest<com.appspot.myanhub_collabra.collabra.model.User> {

      private static final String REST_PATH = "user/with/{username}";

      /**
       * Create a request for the method "user.getByUsername".
       *
       * This request holds the parameters needed by the the collabra server.  After setting any
       * optional parameters, call the {@link GetByUsername#execute()} method to invoke the remote
       * operation. <p> {@link GetByUsername#initialize(com.google.api.client.googleapis.services.Abstra
       * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param username
       * @since 1.13
       */
      protected GetByUsername(java.lang.String username) {
        super(Collabra.this, "GET", REST_PATH, null, com.appspot.myanhub_collabra.collabra.model.User.class);
        this.username = com.google.api.client.util.Preconditions.checkNotNull(username, "Required parameter username must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetByUsername setAlt(java.lang.String alt) {
        return (GetByUsername) super.setAlt(alt);
      }

      @Override
      public GetByUsername setFields(java.lang.String fields) {
        return (GetByUsername) super.setFields(fields);
      }

      @Override
      public GetByUsername setKey(java.lang.String key) {
        return (GetByUsername) super.setKey(key);
      }

      @Override
      public GetByUsername setOauthToken(java.lang.String oauthToken) {
        return (GetByUsername) super.setOauthToken(oauthToken);
      }

      @Override
      public GetByUsername setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetByUsername) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetByUsername setQuotaUser(java.lang.String quotaUser) {
        return (GetByUsername) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetByUsername setUserIp(java.lang.String userIp) {
        return (GetByUsername) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String username;

      /**

       */
      public java.lang.String getUsername() {
        return username;
      }

      public GetByUsername setUsername(java.lang.String username) {
        this.username = username;
        return this;
      }

      @Override
      public GetByUsername set(String parameterName, Object value) {
        return (GetByUsername) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "user.insert".
     *
     * This request holds the parameters needed by the collabra server.  After setting any optional
     * parameters, call the {@link Insert#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.myanhub_collabra.collabra.model.User}
     * @return the request
     */
    public Insert insert(com.appspot.myanhub_collabra.collabra.model.User content) throws java.io.IOException {
      Insert result = new Insert(content);
      initialize(result);
      return result;
    }

    public class Insert extends CollabraRequest<com.appspot.myanhub_collabra.collabra.model.JsonMap> {

      private static final String REST_PATH = "user";

      /**
       * Create a request for the method "user.insert".
       *
       * This request holds the parameters needed by the the collabra server.  After setting any
       * optional parameters, call the {@link Insert#execute()} method to invoke the remote operation.
       * <p> {@link
       * Insert#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.myanhub_collabra.collabra.model.User}
       * @since 1.13
       */
      protected Insert(com.appspot.myanhub_collabra.collabra.model.User content) {
        super(Collabra.this, "POST", REST_PATH, content, com.appspot.myanhub_collabra.collabra.model.JsonMap.class);
      }

      @Override
      public Insert setAlt(java.lang.String alt) {
        return (Insert) super.setAlt(alt);
      }

      @Override
      public Insert setFields(java.lang.String fields) {
        return (Insert) super.setFields(fields);
      }

      @Override
      public Insert setKey(java.lang.String key) {
        return (Insert) super.setKey(key);
      }

      @Override
      public Insert setOauthToken(java.lang.String oauthToken) {
        return (Insert) super.setOauthToken(oauthToken);
      }

      @Override
      public Insert setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Insert) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Insert setQuotaUser(java.lang.String quotaUser) {
        return (Insert) super.setQuotaUser(quotaUser);
      }

      @Override
      public Insert setUserIp(java.lang.String userIp) {
        return (Insert) super.setUserIp(userIp);
      }

      @Override
      public Insert set(String parameterName, Object value) {
        return (Insert) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Collabra}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Collabra}. */
    @Override
    public Collabra build() {
      return new Collabra(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CollabraRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCollabraRequestInitializer(
        CollabraRequestInitializer collabraRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(collabraRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
